### ISSUE TITLE
This stool entity is not active (can't spawn a heat exchanger)

### ISSUE THREAD

**Issue by ed588** [spacebuild/spacebuild#104]
I am on a spacebuild map, spacebuild is working
however when i try to place a temperature exchanger it says in the bottom right corner "This Stool Entity is not active" with a red background for a split second. In the console it also says in yellow text "This Stool Entity is not active".
I can spawn other things, such as air exchangers, fine.

**Comment by X-Coder** [comment]
Whats the map name?
Does it happen on the whole map?

**Comment by ed588** [comment]
The map is sb_gooniverse, it was reccomended somewhere
yes, it happens all over the map, as far as i can tell

**Comment by ed588** [comment]
I had some other plugins, they were conflicting. Disabling them fixed the issue :smile:

**Comment by X-Coder** [comment]
You know which one caused the conflict?
