### ISSUE TITLE
Problem setting up server.

### ISSUE THREAD

**Issue by UnknownShifter** [spacebuild/spacebuild#108]
So, a buddy and I decided to put up a Spacebuild server.  All files are uploaded and mounted onto the server, except for one teensy weeny detail.  The gamemode won't initialize, and there is no gamemode folder.  How would I go about mounting the latest master version into a server?

Edit: Nevermind, fixed it.

**Comment by generalwrex** [comment]
I'm glad you got the issue resolved, closing the issue ;)
