### ISSUE TITLE
other_screen not working

### ISSUE THREAD

**Issue by X-Coder** [spacebuild/spacebuild#111]
Does anyone know what this screen should actually show for the 4 values?

I tried to fix it, but I don't understand what is meant by "amount / maxamount from other nodes". What should this actually show, whats the difference to the first two values? Hope someone can explain.

When a node, storage battery, and wind turbine is connected, it displays:
**Energy: "0 / 0" and "-59999 / -60000"**
Resource: "amount / maxamount" and "amount / maxamount from other nodes"

1. Bug: amount / maxamount is always 0.
2. Bug: negative values for the other two, because of some code I don't understand in cl_init.lua. 
The numbers are the one of storage cache / network.

If I understand the code in other_screen's cl_init.lua right, it tries to read resources and storages linked directly to the screen for min/max, which is not possible, because you can link both only to a resource node, and the other pair should show the min/max values of linked resource_node / network.

Bugfix:
GetNetTable in GetNetResourceAmount and GetNetResourceCapacity must be changed to RD.GetNetTable in https://github.com/spacebuild/spacebuild/blob/master/lua/caf/addons/client/resourcedistribution.lua

The serverside code of GetNetworkCapacity calls GetNetNetworkCapacity, while the clientside does not and returns 0, this is why the first two values will show 0 I guess. If you copy it to clienside, the first maxamount shows right value, but then other networks maxamount will show 0, because I don't get whats the purpose of the subtraction in other_screen's cl_init.lua right before this line: https://github.com/spacebuild/spacebuild/blob/master/lua/entities/other_screen/cl_init.lua#L263.

**Comment by CaveeJohnson** [comment]
Besides this, resources being monitored can be anything, even if the resource doesn't exist:
![screenshot](https://b.catgirlsare.sexy/q8te.png)

Also the gui is barely functional at best (apart from the on/off button which I fixed yesterday.
[Short video of how broken the GUI is](https://b.catgirlsare.sexy/SBvA.mp4)

Notable issues:
blue 'selection box' is positioned wrong
![screenshot](https://b.catgirlsare.sexy/3Oqx.png)
Adding then removing seems to duplicate everything
![screenshot](https://b.catgirlsare.sexy/NZoT.png)
Lefthand side uses resource names whilst right uses proper names
![screenshot](https://b.catgirlsare.sexy/_Gw1.png)
Lefthand side does not actually appear until updating it (adding resource)
![screenshot](https://b.catgirlsare.sexy/V72n.png)
![screenshot](https://b.catgirlsare.sexy/IJIN.png)

## Most of this applies to the pump's GUI too.

**Comment by X-Coder** [comment]
Fixed both bugs I posted above myself. I will commit them after some more tests.
Now only the GUI needs to be fixed.

Whats the purpose of adding non registered resources using the text field?

**Comment by X-Coder** [comment]
The bugs have been fixed by these commits:
8134717b50c13f53461e89ef36366f0e7a754803 Fixes other_screen's GUI 
57727db619947998331d5b78767768ed62562c34 Fixed wrong values on other_screen
c94498494c0c09daae545e8876bad62ad41afc9e Adds duplication support to other_screen
224332d3d8bdc48bf6d646711bdc658a599e280a Fixed resource lines not showing up in left ListView
eabbd38a8983ea402e67deaf5156343f1f0fbb57 Removed text field
