### ISSUE TITLE
New website for everything Spacebuild and SBEP

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/spacebuild#115]
Creating a new website/forum for Spacebuild and SBEP where people can ask questions, request features, learn how to use spacebuild, and much much more!

I'll need more people with some feedback on this! ;D

Current developer home of the new website;
http://spacebuild.x-coder.de

Note: this is a temporary domain!
Thanks to XCoder for the dev domain and host!

I would like to gather;

- An affordable domain name that we can all agree on( https://www.godaddy.com/domains/searchresults.aspx?checkAvail=1&tmskey=&domainToCheck=spacebuild)

- People to come up with forum topics and people to answer questions! ;)
- Someone to host( the websites home)
> @SnakeSVx has offered the use of his VPS since he has extra resources

- Administrators and Modders for the website and forum
> @generalwrex
- Web Devs (html, js, php, etc)
> @X-Coder

- Server Management ( keeping the site/forum updated, working, and online! Ubuntu)
> @X-Coder
> @generalwrex

If you would like to be part of this, leave a comment with what you could provide for this adventure and i'll add you to the list above!

**Comment by noobanot** [comment]
Comment on that

**Comment by CaveeJohnson** [comment]
Certainly, github provides space for a wiki and issue tracker but there will undoubtedly be people who want to ask questions or show things which aren't 'issues', making a proper forum very much welcome
Any idea what the domain will be?

**Comment by generalwrex** [comment]
now that is the hard part, i know we cant have Spacebuild.com, thats about 2,500USD  ;)  But I found a few available ones on godaddy here; https://www.godaddy.com/domains/searchresults.aspx?checkAvail=1&tmskey=&domainToCheck=spacebuild

**Comment by X-Coder** [comment]
Good idea. I maybe can help with hosting if needed and scripting. Only with design stuff I'm not much help.

**Comment by generalwrex** [comment]
OP was updated with new information, and a temporary host and domain for developing the new website. Thanks to @X-Coder!

**Comment by generalwrex** [comment]
Share this issue around with people to get as many people as possible involved with this, and to hopefully line up some nice fresh topics for the forums

 This is a full community endeavor which would need alot of attention to get it started up and maintained, and it should bring spacebuild back higher than ever before!

I'll be setting up a discord for us here soon, if you guys think it's a good idea

**Comment by generalwrex** [comment]
We have created a Discord server here! Free for all to use.

https://discord.gg/3A4dPhD

**Comment by deathking61** [comment]
i would love to help test it like tell you of any bugs i come across :dagger:

**Comment by generalwrex** [comment]
We structured the forum and its almost ready! what do you guys think, https://spacebuildmod.com/forum/  for ideas you may have about the layout, regsiter for the forum here https://spacebuildmod.com/forum/ucp.php?mode=register  then post your comments about it here https://spacebuildmod.com/forum/viewtopic.php?f=18&t=4
