### ISSUE TITLE
Thoughts on receiving donations for the new website

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/spacebuild#117]
What are your thoughts on me setting up a donation link to help with the website and related things?

I could direct it toward official servers and keeping the website online and also to pay for the domain!

No person would get paid from it, it would only be for the VPS or Server where the website will be located, paying for ddos protection and other things, paying for the perfect domain name

What are you thoughts?

Note: I changed the original content of the post to direct toward maintaining the website with donations and not paying people working on the addon.

**Comment by X-Coder** [comment]
On one side it will motivate people, but on the other side it can lead to closed source projects (based on a open source project), which are not, or hard to maintain if the developer decides later not to keep it going.

For donated developers maybe a donation system with the rule to put the end result as open source?

**Comment by awilliamson** [comment]
I categorically disagree with donations and patreon. The only structure supporting this would be a nonprofit or not for profit organisation where funds are directly owned by the entity and contributors employed by such an organisation.

It's hard to manage and goes against what open source stands for. How do we quantify who gets how much, for instance.

**Comment by generalwrex** [comment]
My bad guys, I wrote this on my phone when I was about to fall asleep.

I meant to put some links up for donations from the community to make sure the website can stay up indefinitely on some server. And maybe a couple Official SB servers. 

In no way did I intend to write down paying people ;)

**Comment by awilliamson** [comment]
Again, the same issues apply. I've looked into non profit based organisations in the UK. It's the only real feasible way of doing it, and its difficult with liability and costs etc. Easiest way is to let the community deal with it. As otherwise it starts getting treated like a shippable product, in this regard we're just helping by providing software for all.

**Comment by generalwrex** [comment]
Yeah I see where you're going, It's why I was looking for thoughts on the subject.  Honestly I didn't even think about it in that regard! Thanks @awilliamson!

**Comment by generalwrex** [comment]
I changed the original content of the post to direct toward maintaining the website with donations and not paying people working on the addon or the website.
