### ISSUE TITLE
Spacebuild Entities

### ISSUE THREAD

**Issue by viral32111** [spacebuild/spacebuild#118]
Hey, so i want to create a spacebuild entity in my addon, but everything i have tried does not work. 

I had a look at the 'resources_api.lua' in the master branch, but i could not find out what to do with the functions inside. So then i copied the 'generator_energy_solar' entity and the 'base_rd3_entity' to the addon. I tried to modify these and it just gave me errors. I also searched it on google but there is literally nothing on this subject.

So can you please give me a full breakdown on how to make my own entities for spacebuild.

EDIT: By spacebuild entity i mean, i would like to know how to make the entity work with resource distribution, so like generating stuff.

**Comment by X-Coder** [comment]
As long we don't have docs available, I would start the same way you did, by looking at the sources of a already similar existent entity and work based on this.

Copying base_rd3_entity sounds wrong, this is some class which is inherited.
What error did you get?

**Comment by viral32111** [comment]
I don't get any errors, the entity just refuses to do anything, i checked the folder structures of the server, checked for any code mistakes, i even reinstalled the server and added back the addons. and still nothing from them

**Comment by X-Coder** [comment]
If you want you can send me the code so I can look why nothing happens.

**Comment by viral32111** [comment]
Here ya go: https://mega.nz/#!lQIHCQZZ!-bXiyHNgsvQYLJ2plrhfuUA7L1MJgG0ZYXlXKrT2m1M

**Comment by viral32111** [comment]
OK!, i have done something. I added 5 these lines of code to the 'generator_energy_solar' entity to make it spawnable: `self:SetModel("models/Combine_Helicopter/helicopter_bomb01.mdl")
	self:PhysicsInit( SOLID_VPHYSICS )
	self:SetMoveType( MOVETYPE_VPHYSICS )
	self:SetSolid( SOLID_VPHYSICS )
	self:SetUseType( SIMPLE_USE )`

Now i can spawn it but my chat gets spammed with 'RD BUG: INVALID ENTID', I have seen this before on the 'Heavy Water Electrolyzer' (before i started to try and make sb entities), so i despawned it and left it.

**Comment by X-Coder** [comment]
RD BUG: INVALID ENTID happens when a entity has no or invalid connection to resource node and a function for resources is called.

**Comment by viral32111** [comment]
Ok, nice to know, also the World Tip for the entity is not showing, What can i do to fix this, or do i have to add `AddWorldTip` in cl_init.lua and grab the values for the resources myself?

**Comment by X-Coder** [comment]
The inherited base_rd3_entity does default WorldTip in its DoNormalDraw, so you don't need to do it yourself.  As long as you don't have set entities GetNetworkedInt("overlaymode") to 0, the Tip should show up when everything is working, not showing up could be for the same reason you get RD BUG: INVALID ENTID.

Only if you want to modify the default World Tip you would need to override the default DoNormalDraw in your own cl_init.lua. You can see in entity other_screen's cl_init.lua (which I'm currently fixing) or resource_node's cl_init.lua in function ENT:DoNormalDraw how override works.

**Comment by viral32111** [comment]
Thanks for telling me, so what can i do to remove the RD BUG: INVALID ENTID, Just connect it to a resource node?, because if so how to other entities work, they don;t give an error on spawned.

**Comment by X-Coder** [comment]
ToolTip should work without connection, the INVALID ENTID means the entity was not registered to ent_table. But why I don't know yet.

**Comment by viral32111** [comment]
well ok, im gunna do a bit more experimenting in the entity and see if i could do something aswell

**Comment by viral32111** [comment]
I get this error in the base_rd3_entity but i have not changed anything:
`[ERROR] addons/spacebuild entities debugging/lua/entities/base_rd3_entity/cl_init.lua:55: attempt to index local 'OverlaySettings' (a nil value)
  1. DoNormalDraw - addons/spacebuild entities debugging/lua/entities/base_rd3_entity/cl_init.lua:55
   2. unknown - addons/spacebuild entities debugging/lua/entities/base_rd3_entity/cl_init.lua:14
`

**Comment by X-Coder** [comment]
You need to setup the overlaysettings in your entity's shared.lua by using list.Set("LSEntOverlayText"...

**Comment by viral32111** [comment]
ok thanks!

**Comment by viral32111** [comment]
is this right `list.Set("LSEntOverlayText", "base_rd3_entity", { HasOOO = true, genresnames = { "energy" } })`

**Comment by X-Coder** [comment]
No, it should contain your entity name instead of the base class.

The file should look like this one:
https://github.com/spacebuild/spacebuild/blob/master/lua/entities/generator_energy_solar/shared.lua

**Comment by viral32111** [comment]
and i put this in base_rd3_entity?, because its already in resource_energy_solar

**Comment by X-Coder** [comment]
No, you don't have to change or put the the base_rd3_entity files into your own entity.

Your entity is using the base_rd3_entity that comes with spacebuild as base class, it gets inherited.

**Comment by viral32111** [comment]
Ok, thanks for the help, So what about this resources_api.lua file? can anything be done with that
