### ISSUE TITLE
Stargate resource transfering

### ISSUE THREAD

**Issue by VXGGOVORTEXGaming** [spacebuild/spacebuild#135]
All resources except Energy refuse to transfer through Stargates with E2 functions and Wire gates.

**Comment by VXGGOVORTEXGaming** [comment]
The wire gates don't work either though.

**Comment by X-Coder** [comment]
@SnakeSVx the e2-stargate functions are of CAP-addon, not wiremod.

This wiremod-code does some sb-stuff, but I don't know what:
https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/wire/client/gmod_tool_auto.lua. Looking through wiremod's sources, I couldn't find more sb related references.

**Comment by X-Coder** [comment]
@SnakeSVx this looks like the right place to look for:
https://github.com/RafaelDeJongh/cap/blob/c07afd0b0e444ab8428b23cb4ad9aacc6a826167/lua/stargate/server/wire_rd.lua

**Comment by SnakeSVx** [comment]
@VXGGOVORTEXGaming  Seems to be a setting in CAP that you have to configure.
When looking through the code it will only transfer resources if they are
- energy
- configered in StarGate.CFG:Get("stargate","res_classes",""); => All lowercase resource names only

Best to read
- https://github.com/RafaelDeJongh/cap/blob/c07afd0b0e444ab8428b23cb4ad9aacc6a826167/lua/data/stargate/config.lua
-  https://github.com/RafaelDeJongh/cap/blob/c07afd0b0e444ab8428b23cb4ad9aacc6a826167/lua/data/stargate/How%20to%20create%20your%20own%20config.lua

**Comment by SnakeSVx** [comment]
@X-Coder  Thanks for the help :)
