### ISSUE TITLE
Environments compatibility layer

### ISSUE THREAD

**Issue by viktorkovarik** [spacebuild/spacebuild#141]
Hey,
I was thinking about adding some kind of compatibility layer for Environments, they use mostly same atmospheric settings since it's derived from sb3 but they also used some different one with which spacebuild doesn't give atmosphere. For instance on sg_quadrants there is no atmosphere on spawn so it makes it hard to play. I think adding that wouldn't take long time and sb3 will be able to use more maps. Environments is dead anyway so at least we could use it's maps.

Regards.
ViktorK

**Comment by viktorkovarik** [comment]
I've managed to do it on my own using built in spacebuild functions... I've forgotten to close it. Thanks anyway for such a great add-on. :-)

**Comment by X-Coder** [comment]
There was an older map version for sg_quadrants, which had support for sb3, but mapper removed it, and changed it to environments later.

I was looking for a solution too a long time ago, specific for this map, didn't think of a compatibility layer.
How did you solve it? Maybe you want to do a workshop addon for your compatibility layer? Or we could think of integrating it into spacebuild if you want?

**Comment by viktorkovarik** [comment]
I've spawned atmosphere using sb3 functions in areas without working atmosphere on sb_quadrants and it's working, I think I can provide that simple code, we can integrate it probably. :-)

**Comment by SnakeSVx** [comment]
Shouldn't be to hard to do, we just need to know what is used to trigger it on those maps and add a small conversion layer. Should be really easy. Just have to find where it's done again in SB3, it's hardcoded somewhere in there. In SB4 it would have been a lot easier.
