### ISSUE TITLE
SB3: Climate regulator environment-errorspam

### ISSUE THREAD

**Issue by X-Coder** [spacebuild/spacebuild#65]
[ERROR] addons/spacebuild/lua/entities/base_climate_control/init.lua:254: attempt to index field 'environment' (a nil value)
  1. Climate_Control - addons/spacebuild/lua/entities/base_climate_control/init.lua:254
   2. unknown - addons/spacebuild/lua/entities/base_climate_control/init.lua:418

There is a lot serverside error spam in file base_climate_control/init.lua when the climate regulator entity device is used, causing lots of lag too.

Same happens for generator_gas entity.

**Comment by viktorkovarik** [comment]
well some easy fix for this? avoid using blackhole cache?
