### ISSUE TITLE
Resource Valve not saving links when duplicated

### ISSUE THREAD

**Issue by johnoldiges** [spacebuild/spacebuild#79]
So when I link two resource nodes via a valve and dupe the setup using adv. dupe 2, the valve is not linked to the resource nodes when I spawn a dupe. if this can be fixed or if you are still working on this, please fix this issue if possible.

**Comment by generalwrex** [comment]
Thanks for the bug report, we'll look into it if we get the repository back in action, just hold on!

**Comment by X-Coder** [comment]
The fix only works for new dupe-saves, because old one didn't store the node or entity relation.

**Comment by johnoldiges** [comment]
Thanks! Is the change live now or if not when will it be?

**Comment by X-Coder** [comment]
It needs to be merged back first by @generalwrex or @SnakeSVx, should be soon ready.

**Comment by johnoldiges** [comment]
Ok, and thanks again!

**Comment by X-Coder** [comment]
This is merged now.
