### ISSUE TITLE
Contributors:  Getting Spacebuild back onto its feet!

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/spacebuild#81]
This is the main issue for both SBEP and Spacebuild about collabs, when we get enough I will update the readme with them.

SBEP issue is at https://github.com/SnakeSVx/sbep/issues/78

If you would like to contribute to getting spacebuild back please leave a comment here to let people know that we'll have active developers!!

The contributors named below are not set in stone, they are just ones I can pull off the top of my head, or have said something in another issue or on steam!

I will update this list as more arrive ;)
# Contributors

```
  -   SnakeSVx ( coder )
  -   generalwrex ( coder )
  -   TheMerkyShadow ( coder )
  -   X-Coder ( coder )
  -   thrimbor ( coder )
```

**Comment by X-Coder** [comment]
Hi generalwrex. nice too see this repository is still alive. I can help on some stuff.

I am currently working on some fixes, like owner issues on doors and docks when using fpp (and other propprotection too I guess). I think I got this working now, but I need to test it further.

Also most of the weapons are already fixed, I started a few years ago and found later https://github.com/David-Ralphsky/SBEP-Weapons who fixed everything. I added some the missing fixes there.

And I did some work on the LiftSystemDesigner-Tool which had a lot issues in multiplayer, I had the feeling it only was made for singleplayer. I'm currently testing this on my dedicated server. The only issue left is, the moving part clips through the owner. I could need a little help on this, couldn't figure out yet where I did break this part.

Also we need to have an eye on file renames or merges where file renames happened, old dupes breaks (or already broken) when we do file renames. SBEP has already a system in place for fixing this (lua\autorun\client\sbep_dupe_fix.lua), we just need to list all file renames to data\sbep\Smallbridge Filename Changes.txt.

For this I integrated the sbep-dupe-fix-script into AdvDupe2 on my Server, so there is a new button which converts old dupes into a fixed copy. The problem with this it required modification of AdvDupe2, so we need to find another way.

But with AdvDupe2 we have another problem which prevents spawning of alot sbep entities with error entity class black listed. We need to find out how to make it work with AdvDupe2. For now I removed the line in lua/advdupe2/sv_clipboard.lua:
```LUA
if ( !scripted_ents.GetMember( Class, "Spawnable" ) and not EntityClass ) then return false end
```
But this is a bad fix.

**Comment by generalwrex** [comment]
Sounds good XCoder! 

We also need to go through the issues on both Spacebuild and SBEP and see if they indeed are still issues.  

Awhile back I spent many hours and fixed pretty much all the SBEP Vehicles, ill see if I can find those fixes again, but this was about 3 years ago, I'm pretty sure I've lost some data xD

**Comment by X-Coder** [comment]
If you plan a workshop release later, should we split the addon in multiple workshop addons like Weapons/Building/Vehicles for example? And split it on github too? Or first merging everything in this repository (or sbep) and maybe split later? Think last one makes more sense for now.

Is workshop size limit (~64MB) still a problem? Or has this been fixed/increased?

**Comment by TheMerkyShadow** [comment]
Just adding on to what x-code was saying. The workshop upload limit is not 64mb anymore. However, for some reason on Linux maybe Windows haven't tested the add workshop id refuses to download a file bigger than 64mb. I suggest we split the workshop into 2 categories.

1) Spacebuild 2) Spacebuild-sbep

**Comment by TheMerkyShadow** [comment]
Also I wanted to let everyone know that there's a huge issue with weapons destroying the atmospheres on planets. I'm trying to find the specific bug that does this but if anyone has any idea how to fix it let me know.

**Comment by X-Coder** [comment]
@TheMerkyShadow, haven't seen this bug on my server. Do you want to test it on my server? If I don't have the issue we could check the differences and make a commit.

**Comment by TheMerkyShadow** [comment]
It only happens once in awhile and I don't know why. I can't replicate it but I know it sometimes happens. The entities are properly setup to deny any localized damage but for some reason they still get destroyed sometimes. I'm unsure on how the maps spawn these entities does anyone know so I can someone save them in a table and check if they are removed and respawn them

**Comment by X-Coder** [comment]
I remember this one, I had this one when I cleaned up the map, it also deleted the atmosphere, currently its not happening any more so I must have fixed this. The climate regulator is causing no atmosphere on planets that had already atmosphere before.

**Comment by Celant** [comment]
I'm going to be perfectly honest here, my Lua knowledge is no way near expert, but it's not beginners either. I'd love to get stuck in helping you guys revive this project, as the thought of having Spacebuild working again is rather exciting to me. My resources are yours to command :)

**Comment by TheMerkyShadow** [comment]
I'll keep trying to replicate the issue and report my progress just wanted to let everyone know what I was doing. Also to add on adv2 the entities should dupe properly...are you sure your using a weapon that's not admin only? Cause that line u posted should work. As long as ENT.Spawnable = true

**Comment by X-Coder** [comment]
The thing I said about the adv2 happens on the entities which could only be spawned using the partassembler toolgun, docks or doors.

**Comment by TheMerkyShadow** [comment]
Well I just checked the door and docking clamp. They have ENT:Spawnable = false they have to be ENT:Spawnable = true. The part spawner should work by itself

**Comment by TheMerkyShadow** [comment]
The reason why it was disabled was probaly because the original authors had no need to make them Spawnable because it was spawned with tool. But recently adv2 within the last year added that check to prevent people from spawning non Spawnable entities.

**Comment by Celant** [comment]
Is it worth setting up a Slack room or similar, as a means to have in-depth discussions?

**Comment by TheMerkyShadow** [comment]
Probaly not

**Comment by TheMerkyShadow** [comment]
I sent a pull request to sbep for the advanced duplicator 2 bug.
I haven't tested the fix but I'm confident that was the problem 
and it will be fixed with this pull request.

**Comment by thrimbor** [comment]
I just quickly added a big addon to my collection, started my server and it was downloading fine, so the 64MB-Linux-problem seems to be gone. Can anybody confirm this?

**Comment by generalwrex** [comment]
Ill make issues on their own threads, hold on guys.

**Comment by generalwrex** [comment]
@Celant Could make a general thread on facepunch, but I don't want to get banned for sneezing ;)  

We can make another issue for casual bug conversation, id like to keep this one for finding collaborators ;)

**Comment by generalwrex** [comment]
I created a facepunch thread for us!  

https://facepunch.com/showthread.php?t=1519499&p=50363396

**Comment by choppingbroccoli11** [comment]
I know that I won't be of any help now, but I'm good at learning things. If there was anything that needed working on, I'd learn how to do it. Please tell me if there's anything I could help with :)

**Comment by Kadah** [comment]
Nice to see this is still going. I won't be of any help anymore but still nice to see its active. :3

**Comment by samcooke98** [comment]
Are you guys going to be working on a new version of spacebuild 4? 
I have some work somewhere on infinite spacebuild maps, may try to find some time to work on it if you guys are creating a new version. - All depends on time though, Next semester of uni is going to be a big one for me

**Comment by generalwrex** [comment]
I believe we are Sam, nice seeing you again!

**Comment by TheAutonomousOne** [comment]
Hey everyone, I'm Autonomous1 from the Facepunch thread. 

Like I mentioned, I have some foley editting and designing (texturing) experience and I wish to help you guys out. I always felt like every surface of all the models felt flat and boring, and extremely repetitive. Now that Spacebuild is being worked on again, I figured I could offer my help. If needed, I'll see if I can put a portfolio together of my texturing work! :)

**Comment by Kadah** [comment]
FWIW, I'm releasing my really old and unfinished final version of Resource Distribution on github. It was supposed to be the core for SB3, but RL work got in the way for several years before I could finish and ended up losing interest in working on gmod projects. I never saw SB3 to release nor had played with it much. I did comeback to SB2 briefly when Yogscast did some videos on it and released a working version on workshop (which appears to be gone again now, lol).

Much like my SB2 core and RD2, it was designed to be very low lag, requiring only minimal operations for normal functions and a pretty lightweight network rebuild on change. Some of the advanced features like power not being a "liquid through a pipe" were never finished.

I don't really remember much on how it worked or was going to, but all of the code is there and might be some useful bits there.

https://github.com/Kadah/SB_RDx

**Comment by generalwrex** [comment]
@TheAutonomousOne That sounds good ;)

@Kadah Awesome, thanks!

**Comment by LtBrandon** [comment]
It's good to see some life going into Spacebuild outside of what we've been doing over at Diaspora (https://diaspora-community.com). I hope that everything goes well for the people working on this, we're not sure if we'll get involved or not. I haven't really looked into what you guys have been doing too much yet, but today I got linked here and figured I'd mention a couple of things.

First of all, just in case this hasn't been figured out by @X-Coder yet, to fix the "entity blacklisted" error with Adv. Dupe 2 you simply need to register the entities with the duplication system. Here is an example:
`duplicator.RegisterEntityClass("mining_drill_rig", SC.MakeEnt, "Data")`
The first argument is the class of the entity, the second is a function that spawns the entity, and after that you can supply variables to be passed into the function(it uses varargs as far as I know). I haven't looked into how it determines what to pass to the function in full, but I'm pretty sure it just checks for entity modifiers matching the arguments.

I've got a ton of fixes sitting around for SBEP. Seeing as people are working on things again I'll go over them at some point and see if there are any that would be helpful. For example, last time I checked the Gyropod that ships with normal SBEP is horrendously laggy(try spawning about 10 of them).

Finally, for quite some time now we've been working on a fork of the "Spacebuild Infinity" project that started up some time ago. I used to be one of the developers for that, and after everyone suddenly stopped working on it the Diaspora community picked it up and has been working on it ever since. We're planning on releasing it back into the wild later this year. I don't know if you guys are planning on working with that or the code it was based on(pretty sure that is in this repository, sb4 branch?), but if you need help with anything specific let me know.

Hey @samcooke98 good to see you around, haven't heard from you in a while heh.

**Comment by X-Coder** [comment]
Hi, nice to see you all and to read all the positive feedback, on facepunch too.

@LtBrandon thank you very much for your hint about RegisterEntityClass, this is the method I used a few days ago to fix the issue, just without wiremod's function, but this is very similar.  And I just updated my post above to mark the fixes I already did and pushed back into master.

**Comment by awilliamson** [comment]
Hey @LtBrandon @samcooke98 @SnakeSVx Nice to see you all again. Do feel free to use whatever resources were available in the SB4 branch. I don't think I'll be able to develop much if at all, I may be starting a new research job soon, and I still have Starfall to maintain.

As for practices required, I would recommend following the 'feature-branch' idea where no 'direct' modifying of the main repo is done, everything is done through PR's from contributors own forks. That way no mistakes can happen, or bad practice.

**Comment by TyanColte** [comment]
I have forked spacebuild and SBEP and have played with it a little bit. Mainly to put something back in there that was there in SB2. The tiny resource caches. I used to use this in conjunction with the Stargate mod pack and I always had one of the puddle jumper ships outfitted with spacebuild stuff. The resource caches were a mighty bit too big to fit on this small ship. In sb2 i would use the small resource caches. Those were removed in SB3+ so I coded them back. if you want i can submit a pull request with my additions. just let me know.

**Comment by SnakeSVx** [comment]
Sure, you can submit a pull request with entities that seem to be missing from older versions.

**Comment by TheAutonomousOne** [comment]
I've had a busy week, but I have managed to put a small portfolio together of all the records I have of my work. Most of it was lost during a PC switch. But anyway, these are all the (worth showing) records of my work: http://theautonomousone.deviantart.com/

**Comment by philxyz** [comment]
If anyone needs a GM13-working copy of SB2 with Linux-compatible filenames, there's a copy that I fixed  up included in "Spacebuild Factions (GlobalRP)" - https://github.com/philxyz/factions/tree/master/gamemodes/spacebuildfactions/gamemode/spacebuild2

**Comment by generalwrex** [comment]
We could put it in the actual sb2 repo if you want, then i can change it to partly supported ;)

**Comment by nirahiel** [comment]
As I said in SBEP thread, i'd like to contribute here too :)

**Comment by generalwrex** [comment]
Lets use the forums now https://spacebuildmod.com/forum
