### ISSUE TITLE
The Spacebuild General Conversation Thread

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/spacebuild#85]
This is for spacebuild conversation topics, but remember to make a new issue if one is deemed necessary for it!

Lets use the forums now https://spacebuildmod.com/forum

**Comment by viktorkovarik** [comment]
Hey, I would suggest to re-add Smallbridge climate regulator. I really hate model of current one, some of those half-life models are really not suitable for ships. Thanks :)

**Comment by viral32111** [comment]
Hey, so i want to create a spacebuild entity in my addon, but everything i have tried does not work. I had a look at the resources_api.lua file but could not find out where to put the functions on it in the entity code. So then i copied the generator_energy_solar entity and the base_rd3_entity to the addon, i tried to modify these and it just gave me errors, So can someone please give me a full breakdown on how to make my own entities for spacebuild. Sorry if i posted this in the wrong section.

**Comment by generalwrex** [comment]
if you could open a new issue with that it would be great ;)

**Comment by viral32111** [comment]
ok will do!

**Comment by generalwrex** [comment]
Lets use the forums now https://spacebuildmod.com/forum
