### ISSUE TITLE
Request: To make the SB variable a global

### ISSUE THREAD

**Issue by philxyz** [spacebuild/spacebuild#98]
If the SB variable in the Spacebuild 3 addon is global, then gamemodes can call SB.GetPlanets(). I have a bug in Spacebuild Factions at the moment since it needs to be able to access that. Maybe there's a better way of doing what I'm doing, however...

**Comment by X-Coder** [comment]
You can access the methods using CAF.GetAddon function.

Examples:
lua_run PrintTable(CAF.GetAddon("Spacebuild").GetPlanets())
lua_run print(CAF.GetAddon("Resource Distribution").GetNetResourceAmount(1, "energy"))

**Comment by philxyz** [comment]
Thanks for the info!

**Comment by generalwrex** [comment]
Yay activity!

**Comment by SnakeSVx** [comment]
There will be a SPACEBUILD global starting from v4.

**Comment by awilliamson** [comment]
@SnakeSVx It may be worth limiting the public API for the new SPACEBUILD global ( may I suggest a rename to SB4 as we'll break previous compatibility anyway ).

Have the new global be accessor's allowing people INTO the core. Then this API can be extended by SB addons to manage their own privacy and protection as they see fit, via the central SB4 layer.

Thoughts?

**Comment by philxyz** [comment]
I'm already setting GM.SPACEBUILD in the gamemode "Spacebuild Factions" to enable the addon (since factions maps begin with fac_ and not sb_

awilliamson, if SnakeSVx went with your option, I would have to set both SPACEBUILD and SB4 to true... except I don't necessarily want SB4 to load. The idea is that each Spacebuild addon (2, 3, 4) will activate if the gamemode sets GM.SPACEBUILD = true

That way the features of spacebuild become active for whatever that gamemode is, and for whichever addon the server has got installed, whether that's v1, v2 or v3

It would however be useful to have an API which returns the Spacebuild version number which can be called from Spacebuild Classic, Spacebuild 3 and Spacebuild 4 so that the gamemode can interrogate easily what addon is there.

**Comment by SnakeSVx** [comment]
They bot have a way to get the version already, in SB 4 (for the first couple of versions) I'm going to make sure that CAF.GetAddon("Spacebuild") also still returns an "addon" table with a get version method on it.

This way it's the same to get the version of spacebuild in both. SB 3 will return a version 3.X, SB4 will return 4.X.
